# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8068e41c4e6170d1e98055a654dda3cdd31e6c13c303845c3827612fa811511fb4c9b8508323c08322ace379f46c774e90b5f7bf1da7cddd30d78a83b099cfbe

test:
  secret_key_base: 31c6fbc052607f6289f1c557cb0ba512093c136fb2d42356cc77885a438760b6644f8ff8392a42ceffe0bedf09b8019f8a8048f20b5d3e4beafa372d35d5f267

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
